Departement:
    type: entity
    table: departement
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        regionId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: region_id
        code:
            type: string
            nullable: false
            length: 3
            fixed: false
            comment: ''
        nomdepartement:
            type: string
            nullable: false
            length: 250
            fixed: false
            comment: ''
            column: nomDepartement
    manyToOne:
        region:
            targetEntity: Region
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                region_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
