Region:
    type: entity
    table: region
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nomregion:
            type: string
            nullable: false
            length: 250
            fixed: false
            comment: ''
            column: nomRegion
    lifecycleCallbacks: {  }
