Ville:
    type: entity
    table: ville
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        departementId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: departement_id
        nom:
            type: string
            nullable: false
            length: 250
            fixed: false
            comment: ''
        cp:
            type: string
            nullable: false
            length: 6
            fixed: false
            comment: ''
        lat:
            type: string
            nullable: false
            length: 12
            fixed: false
            comment: ''
        lon:
            type: string
            nullable: false
            length: 12
            fixed: false
            comment: ''
    manyToOne:
        departement:
            targetEntity: Departement
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                departement_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
