<?php

namespace Proxies\__CG__\Locazik\AnnonceBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Categorie extends \Locazik\AnnonceBundle\Entity\Categorie implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'annonces', 'id', 'categorieName', 'categorieDesc', 'categorieParentId', 'isOnline', 'dateCreation', 'dateUpdate', 'categorieParentName');
        }

        return array('__isInitialized__', 'annonces', 'id', 'categorieName', 'categorieDesc', 'categorieParentId', 'isOnline', 'dateCreation', 'dateUpdate', 'categorieParentName');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Categorie $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorieName($categorieName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorieName', array($categorieName));

        return parent::setCategorieName($categorieName);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorieName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorieName', array());

        return parent::getCategorieName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorieDesc($categorieDesc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorieDesc', array($categorieDesc));

        return parent::setCategorieDesc($categorieDesc);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorieDesc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorieDesc', array());

        return parent::getCategorieDesc();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorieParentId($categorieParentId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorieParentId', array($categorieParentId));

        return parent::setCategorieParentId($categorieParentId);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorieParentId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorieParentId', array());

        return parent::getCategorieParentId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreation($dateCreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreation', array($dateCreation));

        return parent::setDateCreation($dateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreation', array());

        return parent::getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateUpdate($dateUpdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateUpdate', array($dateUpdate));

        return parent::setDateUpdate($dateUpdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateUpdate', array());

        return parent::getDateUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsOnline($isOnline)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsOnline', array($isOnline));

        return parent::setIsOnline($isOnline);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorieParentName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorieParentName', array());

        return parent::getCategorieParentName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorieParentName($categorieParentName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorieParentName', array($categorieParentName));

        return parent::setCategorieParentName($categorieParentName);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsOnline()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsOnline', array());

        return parent::getIsOnline();
    }

    /**
     * {@inheritDoc}
     */
    public function removeAnnonce(\Locazik\AnnonceBundle\Entity\Annonce $annonce)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAnnonce', array($annonce));

        return parent::removeAnnonce($annonce);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnnonces()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnnonces', array());

        return parent::getAnnonces();
    }

}
