locazik_user:
    resource: "@LocazikUserBundle/Resources/config/routing.yml"
    prefix:   /

locazik_categorie:
    resource: "@LocazikAnnonceBundle/Resources/config/routing.yml"
    prefix:   /
    
locazik_admin:
    resource: "@LocazikAnnonceBundle/Resources/config/admin.yml"
    prefix:   /agrume

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@LocazikUserBundle/Resources/config/routing.yml"
    prefix: /compte

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /inscription

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /compte
    
_imagine:
    resource: .
    type:     imagine