locazik_homepage:
    pattern:  /
    defaults: { _controller: LocazikAnnonceBundle:Default:index }


locazik_categorie_lister:
    pattern:  /categorie/lister/
    defaults: { _controller: LocazikAnnonceBundle:Categorie:listerCategorie }
    
locazik_categorie_ajouter:
    pattern:  /categorie/gerer/
    defaults: { _controller: LocazikAnnonceBundle:Categorie:gererCategorie }
    
locazik_categorie_detail:
    pattern:  /categorie/detail/{id}/
    defaults: { _controller: LocazikAnnonceBundle:Categorie:detailCategorie }
    requirements:
        id:  \d+
    
locazik_categorie_modifier:
    pattern:  /categorie/gerer/{id}/
    defaults: { _controller: LocazikAnnonceBundle:Categorie:gererCategorie }
    requirements:
        id:  \d+
    
locazik_categorie_supprimer:
    pattern:  /categorie/supprimer/
    defaults: { _controller: LocazikAnnonceBundle:Categorie:ajaxSupprimerCategorie }  
    
    
    
locazik_annonce_creer:
    pattern:  /annonce/creer/
    defaults: { _controller: LocazikAnnonceBundle:Annonce:creerAnnonce } 
    
locazik_annonce_validation:
    pattern:  /annonce/valider/{id}/
    defaults: { _controller: LocazikAnnonceBundle:Annonce:validerAnnonce }
    requirements:
        id:  \d+
    
locazik_annonce_supprimer:
    pattern:  /annonce/supprimer/{id}/
    defaults: { _controller: LocazikAnnonceBundle:Annonce:supprimerAnnonce } 
    requirements:
        id:  \d+
     
# POUR DES RAISONS DE LOGIQUE, CETTE ROUTE SE TROUVE DANS LE BUNDLE USER
# PERMET la connexion/inscription avant de valider l'ajout d'une annonce
#
#locazik_user_login_before_confirm:
#    pattern:  /annonce/identification/{idAnnonce}/
#    defaults: { _controller: LocazikUserBundle:User:identificationConfirmAnnonce }
#    requirements:
#        idAnnonce:  \d+
    
locazik_annonce_confirmer:
    pattern:  /annonce/confirmer/
    defaults: { _controller: LocazikAnnonceBundle:Annonce:confirmerCreationAnnonce }
  
locazik_annonce_lister:
    pattern:  /annonce/lister/
    defaults: { _controller: LocazikAnnonceBundle:Annonce:listerAnnonce }   
 
locazik_annonce_detail:
    pattern:  /annonce/detail/{id}/
    defaults: { _controller: LocazikAnnonceBundle:Annonce:detailAnnonce }
    requirements:
        id:  \d+
    
locazik_annonce_listerRegion:
    pattern:  /annonces/{nomRegion}/
    defaults: { _controller: LocazikAnnonceBundle:Annonce:listerAnnonceParRegion }
    
    
    
locazik_mot_creer:
    pattern:  /mot-interdit/creer/
    defaults: { _controller: LocazikAnnonceBundle:MotInterdit:creerMot } 
    
locazik_mot_lister:
    pattern:  /mot-interdit/lister/
    defaults: { _controller: LocazikAnnonceBundle:MotInterdit:listerMot } 
    
locazik_mot_supprimer:
    pattern:  /mot-interdit/supprimer/
    defaults: { _controller: LocazikAnnonceBundle:MotInterdit:ajaxSupprimerMot } 
    
    
    

locazik_geo_listedepfromregion:
    pattern:  /geo/listedepfromregion/
    defaults: { _controller: LocazikAnnonceBundle:Geo:ajaxListeDepFromRegion }  