locazik_homepage:
    pattern:  /
    defaults: { _controller: LocazikAnnonceBundle:Default:index }

    
locazik_annonce_creer:
    pattern:  /annonce/creer/
    defaults: { _controller: LocazikAnnonceBundle:Annonce:creerAnnonce } 
    
locazik_annonce_validation:
    pattern:  /annonce/valider/{id}/
    defaults: { _controller: LocazikAnnonceBundle:Annonce:validerAnnonce }
    requirements:
        id:  \d+
    
locazik_annonce_supprimer:
    pattern:  /annonce/supprimer/{id}/
    defaults: { _controller: LocazikAnnonceBundle:Annonce:supprimerAnnonce } 
    requirements:
        id:  \d+
     
# POUR DES RAISONS DE LOGIQUE, CETTE ROUTE SE TROUVE DANS LE BUNDLE USER
# PERMET la connexion/inscription avant de valider l'ajout d'une annonce
#
#locazik_user_login_before_confirm:
#    pattern:  /annonce/identification/{annonceKey}/
#    defaults: { _controller: LocazikUserBundle:User:identificationConfirmAnnonce }
    
locazik_annonce_confirmer:
    pattern:  /annonce/confirmer/
    defaults: { _controller: LocazikAnnonceBundle:Annonce:confirmerCreationAnnonce }
  
#A deplacer dans l'administration !!!
locazik_annonce_lister:
    pattern:  /annonce/lister/
    defaults: { _controller: LocazikAnnonceBundle:Annonce:listerAnnonceAdmin }   
 
locazik_annonce_detail:
    pattern:  /annonce/detail/{id}/
    defaults: { _controller: LocazikAnnonceBundle:Annonce:detailAnnonce }
    requirements:
        id:  \d+
        
# Requete ajax -> permet de récupérer le numéro de téléphone de l'annonce
locazik_annonce_detailGetNumeroTel:
    pattern:  /annonce/detail/getNumTel/{annonceKey}
    defaults: { _controller: LocazikAnnonceBundle:Annonce:ajaxGetNumeroTelAnnonce }
   
locazik_annonce_listerFiltre:
    pattern:  /annonces/{categorieUrlName}/{regionUrlName}/{depUrlName}/{villeUrlName}
    defaults: { _controller: LocazikAnnonceBundle:Annonce:listerAnnonce, categorieUrlName: toutes, regionUrlName: null, depUrlName: null, villeUrlName: null }
    requirements:
        regionUrlName: "[a-zA-Z0-9-]*"
        depUrlName: "[a-zA-Z0-9-]*"
        villeUrlName: "[a-zA-Z0-9-]*"    
        

locazik_geo_listedepfromregion:
    pattern:  /geo/listedepfromregion/
    defaults: { _controller: LocazikAnnonceBundle:Geo:ajaxListeDepFromRegion }  

locazik_geo_listevilles:
    pattern:  /geo/listeVilles/{finder}
    defaults: { _controller: LocazikAnnonceBundle:Geo:ajaxListeCpVille }
    
    
    
    
    
    
    
#########################################################################
#                      GENERATION CHAMPS URL                            #
#########################################################################

genereDepUrl:
    pattern:  /genereDepUrl
    defaults: { _controller: LocazikAnnonceBundle:Geo:genereDepUrl }
    
genereVilleUrl:
    pattern:  /genereVilleUrl
    defaults: { _controller: LocazikAnnonceBundle:Geo:genereVilleUrl }