parameters:
#    locazik_categorie.example.class: Locazik\AnnonceBundle\Example

services:
#    locazik_categorie.example:
#        class: %locazik_categorie.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
