# src/Locazik/AnnonceBundle/Resources/config/validation.yml
Locazik\AnnonceBundle\Entity\ImageAnnonce:
    properties:
        file:
            - File:
                maxSize: 2048k
                maxSizeMessage: 'Taille maximale de fichier autorisée : 2048ko'
                mimeTypes: [application/jpeg, application/png]
                mimeTypesMessage: Le type de l'image n'est pas correct (jpg ou png)