    
locazik_user_login_before_confirm:
    pattern:  /annonce/identification/{idAnnonce}/
    defaults: { _controller: LocazikUserBundle:User:identificationConfirmAnnonce }
    requirements:
        idAnnonce:  \d+