parameters:
#    locazik_user.example.class: Locazik\UserBundle\Example

services:
#    locazik_user.example:
#        class: %locazik_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
