parameters:
#    locazik_user.example.class: Locazik\UserBundle\Example

services:
    locazik_user.registration.form.type:
        class: Locazik\UserBundle\Form\Type\UserRegistrationType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: locazik_userbundle_userregistration }