<?php
// src/Locazik/AnnonceBundle/Entity/Repository

namespace Locazik\AnnonceBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends EntityRepository
{
    public function categoriesOrderbyParent()
    {
        $query = 'SELECT c.id, c.categorieName, c.isOnline, e.parent_id, c.categorieDesc, c.dateUpdate FROM Categorie c, Categorie e ORDER BY COALESCE(c.parent_id, c.id) , c.parent_id IS NOT NULL , c.id';
        $rsm = new ResultSetMapping;
        $rsm->addEntityResult('Locazik\AnnonceBundle\Entity\Categorie', 'c');
        $rsm->addFieldResult('c', 'id', 'id');
        $rsm->addFieldResult('c', 'categorieName', 'categorieName');
        //$rsm->addJoinedEntityFromClassMetadata('Locazik\AnnonceBundle\Entity\Categorie', 'c', 'c', 'parent', array('id' => 'parent_id'));
        //$rsm->addEntityResult('Locazik\AnnonceBundle\Entity\Categorie', 'e', 'c', 'parent');
        $rsm->addFieldResult('c', 'categorieDesc', 'categorieDesc');
        $rsm->addFieldResult('c', 'isOnline', 'isOnline');
        //$rsm->addFieldResult('c', 'parent', 'parent_id');
        
        $qns = $this->_em->createNativeQuery($query, $rsm);
        
        return $qns->getResult();
    }
    
    public function listeCategorieOnline()
    {
        $queryBuilder = $this->_em->createQueryBuilder();
        return $queryBuilder
                ->select('c')
                ->from($this->_entityName, 'c')
                ->where('c.isOnline = :isOnline')
                ->setParameter('isOnline', true);
    }
}