<?php
// src/Locazik/AnnonceBundle/Entity/Repository

namespace Locazik\AnnonceBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends EntityRepository
{
    public function listeRegionOrderBy()
    {
        $queryBuilder = $this->_em->createQueryBuilder()
                ->select('r')
                ->from('LocazikAnnonceBundle:Region', 'r')
                ->where('r.id <> 8')
                ->orderBy('r.nomregion');
        return $queryBuilder;
    }
}